### ISSUE TITLE
Customize Health History App for Clareto workflow

### ISSUE THREAD

**Issue by sanjay1uphealth** [1uphealth/1upwebapp#54]
The current Health History instances send an email with a PDF attachment of the medical record of the user to the Customer's designated email address.
Clareto's business process is different and they would like to consume the medical records in the form of $everything bundle at their endpoint.

See the attached diagram for the flow.
[1up_Clareto_app_flow.pdf](https://github.com/1uphealth/1upwebapp/files/6005726/1up_Clareto_app_flow.pdf)

The handoff will be as follows.
1. Clareto will generate a unique id for each of their users(patients) and add that as a url parameter to the Clareto Health History url. For example: https://clareto.1up.health?id=982379847

2. Clareto will email this link to their user. The user after checking the email (say a day or two later) will click on the above link to reach the Health History App.
3. Health History app will parse the id param.
4. Health History will follow the normal flow until patient confirmation page.
5. After Health History app pulls the full record (after the patient hits 'share medical record' button), it will pull the FHIR $everything bundle for the patient and call the Clareto Endpoint with a POST request & content type appllication/json along with authorization header and the unique id of the patient gathered from step #1

Authenticating with Clareto Endpoint:
End Point: https:// ..TBD
Authorization header format: Authorization: Apikey 89374sjkdhfkjsdhf837498
Headers to send when calling Clareto Endpoint:
"Authorization" : "Apikey $base64encodedapikey"
"user_id": "$user_id_from_clareto"

FHIR $everything bundle crash course :wink:
a. Currently the Health History app creates a user on 1up side
b. After the patient's record is pulled from EHR, the user has a "patient" resource created by the 1up FHIR backend.
c. The Health History app needs to fetch the ['resource']['id'] by calling https://api.1up.health/fhir/dstu2/Patient/ or https://api.1up.health/fhir/stu3/Patient/ 
![image](https://user-images.githubusercontent.com/62340428/108417918-9035aa00-71fe-11eb-9e9a-cf6f0941294e.png)

d. Use the id from **step c** to call $everything endpoint https://api.1up.health/fhir/dstu2/Patient/{id_from_patient_resource}/$everything. This will return the $everything bundle.

Below is an example of $everything bundle
[$everything_response.json.txt](https://github.com/1uphealth/1upwebapp/files/6005725/everything_response.json.txt)

**Comment by sanjay1uphealth** [comment]
[https://app.zenhub.com/files/103162500/f1c24854-b2ab-418f-b37a-0ce34deb01f6/download](https://app.zenhub.com/files/103162500/f1c24854-b2ab-418f-b37a-0ce34deb01f6/download)

**Comment by sanjay1uphealth** [comment]
Issue closed accidentally or a bug in Zenhub

**Comment by Khristina1UpHealth** [comment]
Issue moved to [1uphealth/healthhistory #60](https://github.com/1uphealth/healthhistory/issues/60) via [**ZenHub**](https://www.zenhub.com/)
