### ISSUE TITLE
Update reference docs associated with Bulk Data Export Api

### ISSUE THREAD

**Issue by nikita1uphealth** [1uphealth/1upwebapp#77]
**May 21, 2021**
The below links currently provides documentation for Bulk Data Export Api: 
1. https://1up.health/docs/api/fhir/bulk-data-export
2. https://1up.health/docs/api/fhir/fhir#bulk-data-export

The response of the Bulk Data Export Api includes below content:  
1) "url": "https://analytics.1up.health/bulk-data/dstu2/$export/AllergyIntolerance/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdGFydCI6ImU0NiIsInRvdGFsIjo0LCJ1c2VySWQiOiIxMjM2NzUwNDkifQ.aOqtYWB9Xaup4R80pGjjl4gyaQV9SXRmZaqmnBHp2oI.ndjson"

AND

2) "url": "https://analytics.1up.health/bulk-data/dstu2/$export/Condition/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdGFydCI6ImU0NiIsInRvdGFsIjoxMjAxLCJ1c2VySWQiOiIxMjM2NzUwNDkifQ.LcsXvPEnC0vNr1OwIUi4j98qjRxbT-99dr739r7mjrE.ndjson"

In above examples, each .ndjson file contains information about a specific fhir resource. Our reference documentation should include brief notes for accessing the contents in these .ndjson files. The above specified reference documentation should specify that
(1) a valid access token is required to access the contents of this file,
and since an access token is required (2) reference doc should also mention that a browser cannot be used for invoking this api. 
If a browser is used to access the contents, a 403 status code is output with the error message shown in attachment below. 
![error_accessing_json_file_bulk_export.png](https://images.zenhubusercontent.com/5fbbd2be7a6b64ee0f36d4a0/0aaf91a2-2b40-4349-99cb-cfd09320d65b)

For making the customer experience easier and smooth, notes for accessing these file's contents should be added to our reference documents.

**Comment by Khristina1UpHealth** [comment]
updated : https://app.gitbook.com/@1uphealth-1/s/1uphealth/api/fhir/bulk-data-export
